[tools]
node = "lts"

[tasks.patch]
description = "Copy counter implementation from example to target directory"
run = """
DIR=svelte-london
cp example/src/routes/+page.server.ts $DIR/src/routes/
cp example/src/routes/+page.svelte $DIR/src/routes/
cp example/src/routes/Counter.svelte $DIR/src/routes/
mkdir -p $DIR/src/routes/api/counter
cp example/src/routes/api/counter/+server.ts $DIR/src/routes/api/counter/
rm -f $DIR/src/routes/+page.ts
"""